### ISSUE TITLE
bulk deleting emails should close email on the right

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#130]
when I  bulk delete emails from the list, and I have the mail open on the right, it stays open although I just deleted it.
When deleting it by the pull-down menu on the right, it closes. So the behavior is both problematic and inconsistent

**Comment by lqust** [comment]
Correct behaviour should be: When I delete the email that is being displayed in the mail pane, no matter from where, it should close the email in the mail pane.

**Comment by bwgpro** [comment]
We were reviewing the beginner stories and verified this seems to be fixed, can someone take a look at it?

**Comment by tiagoferraz** [comment]
It's fixed.
