### ISSUE TITLE
README.md, the command for grabbing pixelated's required dependecies is incorrect for ubuntu.

### ISSUE THREAD

**Issue by SamuelToh** [pixelated-project/pixelated-user-agent#140]
According to the "Quickstart" section of README.md

=>

Dependencies are: node, npm, ruby, bundler, virtualenv, git

On Debian/Ubuntu systems you need:
sudo apt-get install nodejs npm ruby bundler virtualenv git

-------------------------------------
On ubuntu 14.04.
tigerroar@tigerroar-Latitude-E6520:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04

------------------------------------
tigerroar@tigerroar-Latitude-E6520:~$ sudo apt-get install nodejs npm ruby bundler virtualenv git
[sudo] password for tigerroar: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package virtualenv  <== Error'ed

Used `pip` to install virtualenv:
sudo pip install virtualenv.

**Comment by bwgpro** [comment]
There is another problem, this isn't part of the quickstart (the quickstart ends right before that). It was not clear so I changed the README to make it more explicit

**Comment by shyba** [comment]
I am moving this card for QA since we now have a different start guide with other commands.
Please feel free to test again and report errors.
Thank you!
