### ISSUE TITLE
Keep selected email on the mail list selected after message refresh

### ISSUE THREAD

**Issue by albogabriel** [pixelated-project/pixelated-user-agent#153]
Currently, when we refresh the mail list, we lose context of what the selected message is (the email is still open in the right pane, though). We want to keep showing what is the currently select email after refreshing.

**Comment by fbernitt** [comment]
What does selected mail mean? Is it a mail with an activated checkbox? Or is it the currently selected mail, i.e. the highlighted one in a different color. If I click on a mail in my inbox and then click on the inbox icon the highlighting is removed.

**Comment by dudadornelles** [comment]
@apretto to follow up here

**Comment by apretto** [comment]
@fbernitt Selected now means you clicked the mail and have it open on the right side (the mail entry on the list will be highlighted). Keeping it selected means when Pixelated auto-refreshs or you click on the refresh button, the mail will still be highlighted.

Clicking on a tag (Inbox, All, user-created tag) de-selects the mail. This is a behaviour that probably should be implemented (if the mail open on the right pane is on the list, hightlight it no matter how the list was generated; refresh, selecting a tag, etc).
