### ISSUE TITLE
Display encryption status

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-user-agent#165]
This ticket is blocked, because currently we can't get the necessary information from LEAP to display encryption status and the OpenPGP header is not reliable enough.

**Comment by dudadornelles** [comment]
We are working on a monkey-patch to enable this. See: https://github.com/pixelated-project/pixelated-user-agent/commit/79dd84aa83962890ab829105d3af6f114c75b4a0

**Comment by bwgpro** [comment]
A fix for this was started in https://github.com/pixelated-project/pixelated-user-agent/commit/79dd84aa83962890ab829105d3af6f114c75b4a0 and finished in issue #288

Signature status is still broken, but encryption status should be ok for all cases
