### ISSUE TITLE
De-duplicate contacts with same mail address

### ISSUE THREAD

**Issue by shyba** [pixelated-project/pixelated-user-agent#167]
Given that I have some mails from the same contact, but in many different formats (formatted, unformatted -- many names **with same mail address**). 
[**decision**] Should the autocomplete stick with only 1 or show all?
If only one, what criteria to choose the most correct address?
Example:
![screenshot from 2014-11-24 20 17 09](https://cloud.githubusercontent.com/assets/1302078/5175193/2601d2da-7417-11e4-8c5f-e9efe7e59313.png)

**Comment by lqust** [comment]
This is when displaying the autocomplete list. #236 is on the act of sending emails.
