### ISSUE TITLE
Allow custom home folder

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-user-agent#169]
Currently the folder in which the user agent stores is pinned to ~/.leap. A new config parameter --pixelated-home should make it possible to change this location.

When run in dispatcher setup the home folder currently is stored within the container image. If we would want to update the user agent version by switching to a new container, this currently means, that the database needs to be completly downloaded again. To avoid this problem and to allow container recreation on each agent start, this new option should allow to store the soledad database in a mounted folder.

**Comment by shyba** [comment]
Worked. The option is --home and I removed ~/.leap before forcing --home to /opt/leap. No folder is created on the default location and all files are on /opt/leap as expected. After removing this option, everything came back to default ~/.leap.
