### ISSUE TITLE
Remove bounced addresses from suggested contacts

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#174]

**Comment by pmaia** [comment]
To identify bounced addresses we are relying on two headers that came in all bounce messages we could observe: **delivery-status** and **Final-Recipient**. The first one tell us that the message in question is a bounce message and the second one to what address the message was originally sent. The **Final-Recipient** header is described on RFC3798.

There are still some questions to answer:

* Should we remove bounced addresses for the bounce messages that we add internally to our inbox as part of smtp error handling (see mails_resources.py)? If so, we'll need to make the bounce message compliant with the format we expect

* Should we also filter the *from address* of bounce messages from contacts suggestions? Ex.: MAILER_DAEMON@try.pixelated-project.org. Is yes, I suggest to create a different issue for that.

* While the bounce message doesn't arrive the user will see the mail address on the contacts suggestion. After the bounce messages arrives the address will suddenly disappear from the suggestions. Is this strange, @albogabriel ?

* What if a mail address exists and we get a bounce for a temporary error? Should we only remove from the suggestions the addresses related with permanent failures (see RFC3463)? Right now we are removing all the bounce addresses from the suggestions

**Comment by tiagoferraz** [comment]
I think it is strange for the email disappear from contact suggestions. Since we are using the color to indicate the level of security of a recipient, we could also use a color to indicate a contact from a bounced email.

**Comment by bwgpro** [comment]
Some of my opinions

1st bullet - I think we should not change the messages we sent, even if
there was a bounce, you send a message to a group of people, you should
have history of that.

2nd bullet - I think so, because those addresses usually have no mailboxes
associated with them

4th - ​I don't see a point​ in removing contacts because of temporary
errors, because that means the address is valid, but something prevented
the mail from being delivered (mailbox is full, server is under heavy load,
try later, those types of things).

Kind regards,

Bruno W.G.
bwgpro@gmail.com

**Comment by lqust** [comment]
I agree with Bruno in all his remarks. Regarding the 3rd bulled (which he didn't spoke about), I think that if we deliver the bounce address message to the user, that is enough to "explain" why the contact address was removed. And it's not like he or she will be comparing the suggested contacts anyway.

**Comment by shyba** [comment]
2th - Implemented. Mailer daemons are also filtered now.
4th - Implemented. Checking now if error codes starts with 5.
1st - Nothing changes then.

It is ready for QA, but I am still thinking (looking for) edge cases. I can add them or discuss later.
