### ISSUE TITLE
Drafts without any information aren't opened on filter ALL

### ISSUE THREAD

**Issue by fabiopio** [pixelated-project/pixelated-user-agent#181]
##### Steps
1 - Click in "Compose", don`t put any information
2 - Click in "Save Draft", see that the draft is salved
3 - Select the side filter "ALL"
4 - Try to open the last email saved by draft on step 2

##### Results
- Verify that the new email saved as draft and without any information is hard to open. (After I saw that is because the user have to click in the word "you", but isn't intuitive):

![screen shot 2014-12-09 at 2 46 45 pm](https://cloud.githubusercontent.com/assets/1228692/5361370/ee317cb0-7fb1-11e4-9852-3514676c2769.png)

*Sugestion:* Emails without any information (subject, body...), doesn't need be saved as draft.

**Comment by tiagoferraz** [comment]
It is already fixed.
