### ISSUE TITLE
It is possible to create empty tags

### ISSUE THREAD

**Issue by fabiopio** [pixelated-project/pixelated-user-agent#184]
Try to create a new tag that is empty or just contains spaces, see that this tag is created and shown empty:

![screen shot 2014-12-09 at 6 13 19 pm](https://cloud.githubusercontent.com/assets/1228692/5364928/e2762bce-7fce-11e4-97cf-1ac3bd210f78.png)

**Comment by cz8s** [comment]
tested on latest debian package. 
Tags consisting of spaces are still possible.
Testing with latest source now ...

**Comment by cz8s** [comment]
![screen shot 2015-01-27 at 16 25 16](https://cloud.githubusercontent.com/assets/369402/5921027/2967d0c6-a641-11e4-8d60-78798383bc61.png)

**Comment by dudadornelles** [comment]
It won't work, it needs a bit of fixing. Right now we are just checking for
empty tags but not for only spaces. Instead of checking tag != "" we must
check !/^\s*$/.test(tag)

**Comment by bwgpro** [comment]
We should strip spaces on the labels. maybe using $.trim on javascript and ' '.strip on python

**Comment by cz8s** [comment]
Validating input is always a gold idea :)
