### ISSUE TITLE
Improve user feedback for invalid email addresses

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-user-agent#189]
spin off from issue #168
## what 
If I only enter invalid email addresses and click the send button, then the button state changes to sending, even if it is not sending due to invalid addresses. Button should not be enabled if invalid emails are in the list.
## I expected that
Validation on emails should run when the email is tokenized and token background should change to #F7E8AF

**Comment by tiagoferraz** [comment]
The Send button is not stuck on "Sending" anymore if the email is Invalid, but it is enabled if any string is typed and get stuck in "Sending" if any other error occurs ("problems talking with server" for example) and there is no workaround.
