### ISSUE TITLE
Highlighted in results doesn't match what search engine is actually looking for

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-user-agent#192]
When I search for parts of words, Javascript highlights all matches it finds on the current page, even though woosh doesn't search for parts of words and thus doesn't produce any results.

*Example:*
When I search for "any" I find an email with the segment "Any one seeing too many open bugs".
Currently the highlight is "**Any** one seeing too m**any** open bugs"
It should be  "**Any** one seeing too many open bugs"

**Comment by alabeduarte** [comment]
Just to let you know that I'm working on this.

Thanks

**Comment by bwgpro** [comment]
Awesome! Feel free to create a pull request when you finish or  if you want someone to review what you're doing

**Comment by bwgpro** [comment]
This seems to be working, can someone validate it?

**Comment by tiagoferraz** [comment]
Validated! It is not searching tags, but there is a defect for this.
