### ISSUE TITLE
Showing "null" on Subject to mail replied

### ISSUE THREAD

**Issue by fabiopio** [pixelated-project/pixelated-user-agent#209]
When some mail without subject is replied, this mail shows subject like "null":

![screen shot 2014-12-18 at 6 24 04 pm](https://cloud.githubusercontent.com/assets/1228692/5495205/cbe74f44-86e2-11e4-97ea-66cd81071f31.png)

I think that an good idea is create an treatment like in Draft (showing "< No subject >"):

![screen shot 2014-12-18 at 6 12 37 pm](https://cloud.githubusercontent.com/assets/1228692/5495038/368362ea-86e1-11e4-886e-c29ce337c9c8.png)

**Comment by lieblingswelt** [comment]
we could not replicate the "null" subject in Inbox. Instead we receive an empty subject "RE: ".

**Comment by fabiopio** [comment]
Hey @lieblingswelt, an empty subject like "RE:" it's an correct behavior for this case, but doesn't occur. Always when you reply an mail, the empty subject will show with "null".

**Comment by fabiopio** [comment]
Disregard it, now it's ok:

![screen shot 2015-01-06 at 1 43 38 pm](https://cloud.githubusercontent.com/assets/1228692/5630950/a93f97b4-95a9-11e4-8d55-d2ce08fa9303.png)
