### ISSUE TITLE
useragent from .deb fails with "pkg_resources.DistributionNotFound: service-identity"

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#210]
this is today's useragent installed from .deb on fresh debian wheezy vagrantbox, following the instructions from the README.md: 

```
root@leap-debian:~# pixelated-user-agent --register try.pixelated-project.org varac01
Traceback (most recent call last):
  File "/usr/bin/pixelated-user-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: service-identity


root@leap-debian:~# apt-cache policy pixelated-user-agent
pixelated-user-agent:
  Installed: 0.3~643.gbp8e5741
  Candidate: 0.3~643.gbp8e5741
  Version table:
 *** 0.3~643.gbp8e5741 0
        500 http://packages.pixelated-project.org/debian/ wheezy-snapshots/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by cz8s** [comment]
I started with testing the dispatcher packages in https://github.com/pixelated-project/pixelated-dispatcher/issues/16
We should do the same here

**Comment by varac** [comment]
ok, the go server already tests the installation and execution of the useragent: http://go.dfi.local:8153/go/admin/pipelines/pixelated-user-agent/stages/test_package/settings

**Comment by fbernitt** [comment]
Bruno wrote:

Hey people,

  Considering the problems we were having and that the service_identity
package is unavailable on wheezy I decided to remove it.

  The practical outcome is that the TLS hostname verification may reject
some valid hostnames. Considering that by default twisted is conservative
in verifying hostnames (it will reject instead of accepting when not sure)
, this change does not open a security risk.
