### ISSUE TITLE
Test soledad-client 0.6.3 deb package against soledad-server 0.6.3

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#211]
unstable.bitmask.net has soledad-server 0.6.3 installed as deb.
We should test soledad-client 0.6.3 against it.

However, the current pixelated-user-agent deb is broken, see #210

**Comment by dudadornelles** [comment]
Running it from sources works but breaks lots of tests (integration), my guess is because now soledad is more 'threaded', so we get I/O errors when writing to soledad.

**Comment by varac** [comment]
currently blocked by the python-cryptography dependency see #227

**Comment by dudadornelles** [comment]
Also integration tests are breaking with the new version

**Comment by varac** [comment]
i just tried with latest .deb vesion ```0.3~741.gbp231de0``` and it works in my vagrant box.

**Comment by dudadornelles** [comment]
It works for me too:

vagrant@vagrant-debian:/vagrant$ apt-cache policy soledad-client
soledad-client:
  Installed: 0.6.3+0~20141222183609.75+wheezy~1.gbp23cbe0
  Candidate: 0.6.3+0~20141222183609.75+wheezy~1.gbp23cbe0
  Version table:
 *** 0.6.3+0~20141222183609.75+wheezy~1.gbp23cbe0 0
        500 http://deb.leap.se/0.6/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
vagrant@vagrant-debian:/vagrant$ apt-cache policy soledad-common
soledad-common:
  Installed: 0.6.3+0~20141222183609.75+wheezy~1.gbp23cbe0
  Candidate: 0.6.3+0~20141222183609.75+wheezy~1.gbp23cbe0
  Version table:
 *** 0.6.3+0~20141222183609.75+wheezy~1.gbp23cbe0 0
        500 http://deb.leap.se/0.6/ wheezy/main amd64 Packages
        100 /var/lib/dpkg/status
