### ISSUE TITLE
Can't edit a draft when I selected it in the "All" mailbox

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#214]
Currently when I find a draft in the "All" mail box, I cannot continue composing it and send it. I should be presented with the edit view in the mail pane (like when I find on the "Drafts" mailbox).

In the future we may want to mark them as drafts in the mail list or allow some different behaviours there but this is not included here.

**Comment by dudadornelles** [comment]
Solved by 26be3c59b174eb9f1a6f73c67489738c7517ce8c I believe? /cc @rafaelzlisboa

**Comment by tiagoferraz** [comment]
It is working, so I'm adding this defect to QA to be closed during stand up.
