### ISSUE TITLE
Results to search are not highlighted after reload

### ISSUE THREAD

**Issue by fabiopio** [pixelated-project/pixelated-user-agent#221]
When I search for some word, the result and the words are highlighted:

![screen shot 2015-01-06 at 2 35 26 pm](https://cloud.githubusercontent.com/assets/1228692/5631829/d1068b20-95b0-11e4-9c8a-b3c69fa04c8e.png)

But after the mail list is reloaded (some seconds after), the words are not highlighted anymore:

![screen shot 2015-01-06 at 2 35 36 pm](https://cloud.githubusercontent.com/assets/1228692/5631834/d9fa0cca-95b0-11e4-93e9-2b54a5f913a1.png)

**Comment by dudadornelles** [comment]
s/detached/highlighted

**Comment by fbernitt** [comment]
Works for us, tested with latest user-agent on two different machines.

**Comment by fabiopio** [comment]
Retested, not occurs more, closing this issue.
