### ISSUE TITLE
Showing invalid new mail in inbox (two mails unread)

### ISSUE THREAD

**Issue by fabiopio** [pixelated-project/pixelated-user-agent#222]
Always that I login within my account, is showing two mails unread. 

This information is not truth, because all mails are read.

I saw that with another account (Neissi's mail) and occurs the same.

![screen shot 2015-01-06 at 2 05 33 pm](https://cloud.githubusercontent.com/assets/1228692/5631299/a03d7fca-95ac-11e4-8854-19fb926dfca5.png)

**Comment by dudadornelles** [comment]
That happens sometimes in the dispatcher setup too. We need to investigate.

**Comment by fbernitt** [comment]
Current state:

The count on the tag list gets only updated if the list of tags gets refreshed. If  a mail is marked as read/unread its not updated automatically. 

To verify this behaviour, add a new tag to a mail after changing its read state and the tag count is updated immediatly.

**Comment by fabiopio** [comment]
Yes @fbernitt, I see that the count on tag list is updated when the tags gets refreshed (eg.: after changing its read state).

Maybe the problem is with my account, once the service returns more mails than is listed on UI. In my mail list returns 23 mails, but on service returns 27 (this difference of 4 mails are displayed as unread). 

![screen shot 2015-01-12 at 4 05 43 pm](https://cloud.githubusercontent.com/assets/1228692/5707979/598be8d8-9a74-11e4-9e12-605f18349d0d.png)

Do you know how can I clean my account to test if the problem is really with deprecated mails?

**Comment by fbernitt** [comment]
Currently the account is not useable, see Issue #232 

This ticket has to wait till we can observe the described problems in another account.

**Comment by lqust** [comment]
Closing for now.
