### ISSUE TITLE
Option to install useragent from .deb in vagrant

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#224]

**Comment by varac** [comment]
works, see my vagrant_multimachine branch

**Comment by varac** [comment]
damn, starting the useragent on wheezy fails, see #226 
i'll block this issue until #226 is resoved.

**Comment by varac** [comment]
oh, before merging, i would like to squash some commits. so please QA and ping me so i can merge.

**Comment by varac** [comment]
this is the branch i pushed to: https://github.com/varac/pixelated-user-agent/tree/vagrant_multimachine

**Comment by dudadornelles** [comment]
waiting for the merge

**Comment by varac** [comment]
merged

**Comment by varac** [comment]
works-for-me(tm)

**Comment by dudadornelles** [comment]
We will need to backport python-whoosh 2.5.7 for this to work. It is the only non-wheezy version we need right now (other than the ones that were already backported as leap.* deps).

@cz8s can we do that?

**Comment by dudadornelles** [comment]
So turns out I had the wrong story number in my mind. All my checkins on 224 are actually related to https://github.com/pixelated-project/pixelated-user-agent/issues/240
