### ISSUE TITLE
find a way to create the whoosh key without python-cryptography

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#227]
We cant use python-cryptography in our debian packages.
We need another way to create the key

**Comment by cz8s** [comment]
See #226

**Comment by cz8s** [comment]
I created a pynacl package. We can use that for creating the keys if we want to.

**Comment by shyba** [comment]
Technical details from nacl secret key encryption
=========
* Random generation: /etc/urandom [Source](http://doc.libsodium.org/generating_random_data/README.html)
* Key generation and cipher algorithm: Poly1305 MAC and Salsa20 [Source](http://pynacl.readthedocs.org/en/latest/secret.html#algorithm-details)

**Comment by cz8s** [comment]
how does leap create their key to encrypt the local sqlite database? 
We could use the same mechanism or even the same key ?

**Comment by varac** [comment]
someone should get in contact with ivan/kali from leap, how bitmask creates the key. i spoke to ivan yesterday, but it would be better if someone who will actually implement this into the useragent speaks directly with him.

**Comment by fbernitt** [comment]
Hey,

I wonder why we need to add an extra crypto library here? The mails are stored in the soledad database and encrypted using sqlcipher. Can't we just use the same crypto libraries for that? IMHO we don't gain more security by encrypting the index in a different way?

**Comment by shyba** [comment]
I am looking how its done there and checking for already present crypto libraries. I also agree that reusing some lib should be better.

**Comment by dudadornelles** [comment]
https://github.com/leapcode/soledad/blob/5f2781c807ba5c645895cf6c42321eb5bcfeef15/client/src/leap/soledad/client/crypto.py#L166

On Tue, Jan 13, 2015 at 2:31 PM, Victor Shyba <notifications@github.com>
wrote:

> I am looking how its done there and checking for already present crypto
> libraries. I also agree that reusing some lib should be better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated-project/pixelated-user-agent/issues/227#issuecomment-69773037>
> .
>



-- 
Duda Dornelles
Software Developer/Consultant @ ThoughtWorks

**Comment by shyba** [comment]
Now using SoledadCrypto (Salsa20 with generated IV appended on file on each encrypt operation). 
Currently, **no message authentication** is used on whoosh files. NaCl and Cryptography had it, but MAC on SoledadCrypto is based on document attributes.

I am looking how to do this without a SoledadDocument using hmac or poly1305 or anything easy.
