### ISSUE TITLE
De-duplicate recipients with same mail address

### ISSUE THREAD

**Issue by shyba** [pixelated-project/pixelated-user-agent#236]
Currently, if we put the same mail a bunch of times the UA doesnt check for duplicity and sends a bunch of repeated mails to the user. We should check if the mail is already on the list and remove duplicated entries.

Steps:
Send a mail to yourself with your own mail copied X times on To, Cc and Bcc.
You will send 10 emails, where you should be sending just 1.

**Comment by dudadornelles** [comment]
Also, notice that

"Duda Dornelles <duda@try.pixelated-project.org>" is the same as "Duda <
duda@try.pixelated-project.org" and "duda@try.pixelated-project.org".

@lqust, any ideas on which one to use? (The longest?)

Cheers,

On Tue, Jan 20, 2015 at 12:46 PM, Victor Shyba <notifications@github.com>
wrote:

> Currently, if we put the same mail a bunch of times the UA doesnt check
> for duplicity and sends a bunch of repeated mails to the user. We should
> check if the mail is already on the list and remove duplicated entries.
>
> Steps:
> Send a mail to yourself with your own mail copied X times on To, Cc and
> Bcc.
> You will send 10 emails, where you should be sending just 1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated-project/pixelated-user-agent/issues/236>.
>



-- 
Duda Dornelles
Software Developer/Consultant @ ThoughtWorks

**Comment by lqust** [comment]
To send, it doesn't matter we should pick the first and ignore the rest. Make sure all are added to the auto suggests list (suggested list was implemented in #60).

**Comment by lqust** [comment]
Related to #173 and #174

**Comment by shyba** [comment]
Maybe related: #167

**Comment by shyba** [comment]
This bug is caused when sending the email. #167 is the one that you are discussing, there the contacts in contact list are repeated.
There is no need for a contact list to reproduce this one. Trying to be more clear:
You will repeat addresses by your will (not by suggestion).
After clicking 'Send' the bug will occur on server side: repeated emails are fired. One for each repeated address.
Someone needs to investigate why sending a single mail fires multiples mails to repeated address.
IMHO, de-duplication on server side may solve it, but this is a hypothesis.

**Comment by lqust** [comment]
This is on the act of sending emails. #167 is when displaying the autocomplete list.

**Comment by bwgpro** [comment]
Pull request #263 fixes this, just review it and validate that it works
