### ISSUE TITLE
Add transition while user agent interface loads

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#237]
Currently the page renders with missing buttons, misaligned content, and broken links before it comes into a usable state. We would like to have an effect as attached be displayed while the page loads. We should still have a progress bar/loading text if at all possible. Having this in place should be enough to pass this story, but if you can work with me to add these features, let''s talk. *Important notice:* because it is all SVG, it can be made responsive. There are row/column attributes and width/height attributes that can do the trick, but I couldn't make it work and need stories in the pipleine :o) Once aggain, happy to pair if we can find the time.

https://github.com/pixelated-project/pixelated-user-agent/tree/master/web-ui/Interstitial%20Design

**Comment by bwgpro** [comment]
Loading screen is missing parts on different screen sizes, should we fix that on this issue or open a new issue for that?

**Comment by fbernitt** [comment]
Looks good but as bwgpro pointed out, does not auto-scale yet.
