### ISSUE TITLE
Simplify left nav menu design

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#239]
Current menu changes radically when it is expanded and it creates confusion and difficulty to navigate. Hopefully this redesign helps that a little. Tag functionality should remain the same. Logout button (#242), logo expansion ( #260) and hover behavior (#261) will be implemented in other stories. See designs below:

Collapsed:
![image](https://cloud.githubusercontent.com/assets/350155/5957820/29ea3e34-a7a5-11e4-903c-ca686cccb9db.png)

Expanded:
![image](https://cloud.githubusercontent.com/assets/350155/5957812/0b04b152-a7a5-11e4-8200-a7f8c3a4736d.png)

**Comment by lieblingswelt** [comment]
I am picking this along with https://github.com/pixelated-project/pixelated-user-agent/issues/242

**Comment by albogabriel** [comment]
Not sure how far into the story @lieblingswelt already is, but wouldn't it make sense to split this into two separate stories - first one handling the expanded/collapsed views keeping things in place, second one making the hover behavior?

If that was done, we'd be delivering value faster and would be able to play #260 right after the first part was done. 

What do you think, @lqust and @lieblingswelt ?

**Comment by lqust** [comment]
I agree! If @lieblingswelt is ok with it, let`s do it!

2015-01-28 21:27 GMT-02:00 Gabriel Albo <notifications@github.com>:

**Comment by lieblingswelt** [comment]
Great: let me un-assign and put this back into analysis. I will implement the logout logic in #242 and then catch up with @albogabriel for the design.

**Comment by albogabriel** [comment]
Cool! I've updated this story now.

**Comment by lqust** [comment]
Make sure to test with Safari and FF, as we had issues with it (message content and header misbehaving)
