### ISSUE TITLE
Design and placement of logout button

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#242]
Logout button is really ugly currently. Please change it to the design below. It should follow the same pattern as #239 

![logout button states](https://cloud.githubusercontent.com/assets/3587497/5843828/7ba877d2-a196-11e4-9b35-0d1b76cba3ee.png)

**Comment by dudadornelles** [comment]
This is a dispatcher story, please open it there.

**Comment by lqust** [comment]
This is the fontawesome: http://fortawesome.github.io/Font-Awesome/icon/sign-out/

**Comment by lieblingswelt** [comment]
changed requirements inorder to unblock as discussed in https://github.com/pixelated-project/pixelated-user-agent/issues/239#issuecomment-71988118

**Comment by bwgpro** [comment]
I was taking a look at this, the only problem was that the logout text was italic, I took the text out of the logout icon and that fixed it.

Looks awesome
