### ISSUE TITLE
provide vagrant images for hacknight

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#244]
the vagrant images should provide a working
env for developing.

* Have the images on usb
* Have the images on a server at werkstatt
* Have the images on the internet

**Comment by fbernitt** [comment]
There is now a command to build a hackday vagrant box:

```
provisioning/build-hackday-box.sh
```
It creates a file hackday-pixelated-user-agent.box in the project root.

To run it, call:
```
vagrant up hackday
```

**Comment by lqust** [comment]
Current issues (out of PoA hackday):
* Low entropy
* Large file
* Slow functional tests

**Comment by cz8s** [comment]
the vagrant machines now always install haveged.
Should fix the entropy problem.
See a46c255006d45ea7b606f94452bff54831f09d8d

**Comment by lqust** [comment]
Created all issues as agreed on standup. @cz8s, please add your comment to #255. I'll close this ticket.
