### ISSUE TITLE
Not decoding UTF-8 username

### ISSUE THREAD

**Issue by pamcdm** [pixelated-project/pixelated-user-agent#248]
When I send an email for myself from gmail, the remitter's name on Pixelated shows like that:

![screen shot 2015-01-24 at 4 35 31 pm](https://cloud.githubusercontent.com/assets/975037/5888483/0e140990-a3e7-11e4-8812-8abb8db9c6e8.png)

**Comment by bwgpro** [comment]
When the display mail has characters out of the ascii range, it falls back to mime encoded words

[This link](https://docs.python.org/2/library/email.header.html) points an easy way to fix it
