### ISSUE TITLE
Vagrant: Speed up key generation

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#250]
we decided to remove the rng-tools hack that used /dev/urandom instead of /dev/random. however, the generation of user keys in vagrant is reaaaallyy slow.

I'd like to install haveged by default on vagrant boxed, because it cares for a full entropy pool, and the security downsides are marginal imo. But we should have a concensus here.

To test speed of random generation, install the rng-tools packages an run ```cat /dev/random | rngtest -c 100``` without haveged installed, and again after you install haveged.
Without haveged, the test takes ages (at least for me).

**Comment by bwgpro** [comment]
We had that problem on the hackday and we had to install rng-tools in all the vagrant boxes on runtime.

Just as a warning, the quality of randomness on the VMs will not be good with rng-tools or with haveged (most of the sources that haveged uses for entropy are emulated in the VMS anyway)

As a more permanent solution, we could try one of the solutions to use the host random pool on the VMs.

**Comment by varac** [comment]
> Just as a warning, the quality of randomness on the VMs will not be good with rng-tools or with haveged (most of the sources that haveged uses for entropy are emulated in the VMS anyway)

True, but i think that comparing between our "hack" (moving from /dev/random to /dev/urandom with rng-tools) is even worse than using haveged. I think it's an ok compromise for most users, but i'm fine with making this optional, if we document it good.

> As a more permanent solution, we could try one of the solutions to use the host random pool on the VMs.

the problem here is that this highly depends on the virtualisation solution, as well as on the host OS. Besides a general good practices document, i think we should no try to implpement such a solution (but maybe i'm too pessimistic here).

**Comment by bwgpro** [comment]
Being practical either solution works for me, haveged uses a prng internally and seed it with random data, for all I've read about the solutions weaknesses and strengths I am comfortable with using haveged

**Comment by cz8s** [comment]
its already done for the vagrant images in pixelated-user-agent.
Did we miss anything? Or is this done already?
See  a46c255006d45ea7b606f94452bff54831f09d8d

**Comment by varac** [comment]
dup of #255
