### ISSUE TITLE
JavaScript dependencies not installed in Hacknight VM

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#252]
Spun out of #244.

Installing dependencies take a long time and hog the internet. Causing problems to hackerspaces. If we can find a way to avoid running NPM and Bower, let's do it.

**Comment by cz8s** [comment]
Just built a new image as explained in https://github.com/pixelated-project/pixelated-user-agent/blob/master/doc/first-steps.md
But  ```/home/vagrant/boxed_node_modules``` does not exist.

Also the user-agent exists with this error:
```pkg_resources.DistributionNotFound: pixelated-user-agent==0.1```
