### ISSUE TITLE
Hacknight VM file is too big

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#253]
Spun out of #244.

We should find a way to make the Hacknight VM file smaller, so it can be easily shared over the network/thumb drives.

**Comment by fbernitt** [comment]
Here I found a small howto about building vagrant boxes. Perhaps some of the tricks described might help us to shrink the box: http://blog.codeboutique.com/post/creating-debian-squeeze-box-for-vagrant

**Comment by cz8s** [comment]
before: 889MB
after:    583MB
