### ISSUE TITLE
Hacknight VMs have very low entropy

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#255]
Spun out of #244.

VMs take a long time to generate keys because of low entropy. There are libraries to do it.

**Comment by shyba** [comment]
Related commit: https://github.com/pixelated-project/pixelated-user-agent/commit/a46c255006d45ea7b606f94452bff54831f09d8d 
@cz8s should the card go directly to Q&A or are there more things to do?

**Comment by cz8s** [comment]
just created a new vagrant box and the key generation inside the box was quick.
And haveged was running

**Comment by bwgpro** [comment]
Just created some keys when testing dev.pixelated and it works like a charm
