### ISSUE TITLE
debian package can't import BufferFile from whoosh.filedb.structfile

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#257]
I just installed the debian package on a fresh debian wheezy.
But I get the error when starting the user-agent

**Comment by cz8s** [comment]
whoosh needs to be at least 2.5.7
Debian stable has 2.3.2

**Comment by cz8s** [comment]
```pip install whoosh``` helps, but we need a package with a valid version

**Comment by dudadornelles** [comment]
I didnt have that problem, I had it installed from our wheezy-backports:

```shell
vagrant@wheezy:~$ apt-cache policy python-whoosh
python-whoosh:
  Installed: 2.5.7-3pixelated3
  Candidate: 2.5.7-3pixelated3
  Version table:
 *** 2.5.7-3pixelated3 0
        500 http://packages.pixelated-project.org/debian/ wheezy-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     2.3.2-2 0
        500 http://http.us.debian.org/debian/ wheezy/main amd64 Packages
```

**Comment by cz8s** [comment]
my fault. I didn't use the packages I built...
Works fine with the correct packages from us.

**Comment by cz8s** [comment]
marking this issue as invalid
