### ISSUE TITLE
Expand logo along with side nav

### ISSUE THREAD

**Issue by albogabriel** [pixelated-project/pixelated-user-agent#260]
(Depends on #239 being done)

As described in story #239, we'll keep the position of the items and expand to show more details; we want the logo to also expand, showing the "Pixelated" text.

When collapsed, the logo should stay as currently is (showing only the cube):
![image](https://cloud.githubusercontent.com/assets/350155/5947141/2ac13c1e-a722-11e4-9fad-9aae16ffda23.png)

Expanded, it should look like this:
![image](https://cloud.githubusercontent.com/assets/350155/5947295/1f3c1138-a723-11e4-8d6f-c8c126500f18.png)

Source file:
https://github.com/pixelated-project/pixelated-user-agent/blob/master/web-ui/app/images/pixelated-logo_symbol_orange.svg

**Comment by pedrovereza** [comment]
The link you provided to the source file is accessible only to ThoughtWorks employees. 

Link to source file in repo:
https://github.com/pixelated-project/pixelated-user-agent/blob/master/web-ui/app/images/pixelated-logo_symbol_orange.svg

**Comment by albogabriel** [comment]
Thanks a lot, @pedrovereza ! I've updated the link now.
