### ISSUE TITLE
Vagrant source runs install script for every ssh connection

### ISSUE THREAD

**Issue by alabeduarte** [pixelated-project/pixelated-user-agent#282]
Hi!

Should it run once, or on demand?

It's annoying to wait for the installer script for every `vagrant ssh` that I make and I think that it's unnecessary since it's already installed.

Thanks

**Comment by tiagoferraz** [comment]
No, Neissi and I noted this started last week.

**Comment by dudadornelles** [comment]
It should only run with `vagrant provision`, I'll take a look

**Comment by dudadornelles** [comment]
We had a `./go setup` in our activate_custom_modules file that runs on bash login. No need for that since that is done at provisioning. If the user wants to keep updating and building the app, etc..., after that, it should be a user choice.

**Comment by dudadornelles** [comment]
@alabeduarte please let me know if it is not happening anymore.

**Comment by alabeduarte** [comment]
Hi @dudadornelles 

I pulled from the latest commit and I'm still seeing the same behaviour, even after reload the machine.
