### ISSUE TITLE
Improve README with detailed provider instructions

### ISSUE THREAD

**Issue by alabeduarte** [pixelated-project/pixelated-user-agent#283]
When I tried to install locally I had to ask for help to configure the provider credentials and understand how it works and which one is used for development.

Would be great for others newcomers get this step detailed on README.

By the way, when I got help, I was instructed to use `try.pixelated-project.org` as a provider. Is this the right provider for development?

Thanks!

**Comment by dudadornelles** [comment]
https://dev.pixelated-project.org/ should be the one used for development.

What do you feel we could add on the README to make it more clear?

Thanks!

**Comment by alabeduarte** [comment]
I would include in the **Quickstart** session some information that tells me where the provider is and how can I sign up for it.

Another option is to put it in the **Service** session which could be clearer saying the same thing as above.

Cheers

**Comment by lqust** [comment]
This will be addressed in https://github.com/pixelated-project/pixelated-platform/issues/65
