### ISSUE TITLE
Make port-forwading use 127.0.0.1 for libvirt provider

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#285]
with the current port-forwarding line in the Vagrantfile:
```
config.vm.network :forwarded_port, guest: 3333, host: 3333
```

vagrant will try to use the configured IP on the guest host setting up port forwarding:

```
varac    24774  0.0  0.0  44424  5288 pts/4    S    15:25   0:00 ssh -o User=vagrant -o Port=22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ForwardX11=no -o IdentityFile=/home/varac/thoughtworks/git/pixelated-user-agent/.vagrant/machines/deb/libvirt/private_key -L localhost:3333:192.168.121.131:3333 -N 192.168.121.131
```

this will not work for me (maybe because i use a libvirt vagrant provider), so i need to use the "guest ip: 127.0.0.1"  in the Vagrantfile.

My question is: why was this disabled ? 
@lqust: it was disabled in your commit 7585c7afe36ff3149d62bef3756f5667059697dc, saying "# do NOT add host_ip in this line. It is not necessary".
this is confusing because before, it was using "guest ip: 127.0.0.1", not *host_ip*.

lqust: could you please try with following line instead:

```
config.vm.network :forwarded_port, guest: 3333, guest_ip: '127.0.0.1', host: 3333
```

**Comment by varac** [comment]
ok, works for me now, please QA if it still works on vbox.

**Comment by bwgpro** [comment]
Blocked while ftp.debian.org is down
