### ISSUE TITLE
Fix unclickable area on email list view

### ISSUE THREAD

**Issue by albogabriel** [pixelated-project/pixelated-user-agent#286]
## Why

Currently, there's an unclickable area on each email on the mailist - the area in green below, which is the link's padding.

![image](https://cloud.githubusercontent.com/assets/350155/6147028/46ca9622-b1da-11e4-8306-6c7694119b13.png)

It's important to make the entire email area clickable (opening the email on the right pane), but keep the checkbox with its current behavior.

## Definition of done
- The entire email compact view (with the exception of the checkbox and the area immediately around it and a couple pixels on top and bottom of the rectangle) is now clickable and the email opens up on the right pane.

**Comment by fbernitt** [comment]
The whole column with the checkbox currently is not clickable. Is that intended?
![not_clickable_around_checkbox](https://cloud.githubusercontent.com/assets/108677/6685280/a14c2ea2-cc98-11e4-98c8-dfe29bb70557.png)

**Comment by albogabriel** [comment]
Hey @fbernitt 

Yes, it is intended :) I'm going to use the area immediately below the checkbox to indicate read/unread or encryption status, still TBD.

But thanks for pointing that out!
