### ISSUE TITLE
Show encryption status when receiving mail from Non-LEAP providers

### ISSUE THREAD

**Issue by bwgpro** [pixelated-project/pixelated-user-agent#288]
When I receive an encrypted mail from an external client the message is not recognized as being encrypted, even though it is decrypted correctly.

The behavior is correct when I send from Leap to Leap

**Comment by tiagoferraz** [comment]
@bwgpro - could you describe how was this implemented? There is something we should pay attention while testing it?

**Comment by bwgpro** [comment]
When we process a new mail, we are checking the encryption status and adding a header named X-Pixelated-encryption-status.

The possible cases are:
- Not encrypted
- Decrypted successfully
- Decryption failed

The best way to test would be to send mail from different mail clients that support encryption (pixelated, enigmail, mutt, <insert client here>) to make sure we are treating all the cases correctly

**Comment by tiagoferraz** [comment]
Thus this show on user interface?

**Comment by bwgpro** [comment]
Yes, it was showing before too, but incorrectly for mails not originating from pixelated itself. It should show correctly on all instances now.

**Comment by lieblingswelt** [comment]
Seems to work for encrypted mails, but NOT for signing.

When sending a signed email from mutt, signature status is not green, even on the first email from that contact.
When sending an encrypted and signed email from the same account to the same account, signature and encryption flags are green (as expected).

Not yet checked for unsigned and encrypted, for failed decryption. Keep you posted.

**Comment by shyba** [comment]
Signature checking will be done in another card.
The fix here is checking for decryption status with a logic implemented based on changes during call to maybe_decrypt methods. This should decouple signature and encryption status and make encryption status reliable.
Signed mails are used just to guarantee that they will not change encryption status, as reported by some bugs in a previous cards:
https://github.com/pixelated-project/pixelated-user-agent/issues/59
https://github.com/pixelated-project/pixelated-user-agent/issues/165

Should we check for duplicate or organize those cards somehow?

**Comment by lieblingswelt** [comment]
Not encrypted, decrypted successfully are fine:
Encryption status is fine when sending from Thunderbird with valid key (uploaded to keyserver)! 

Decryption failed:
When sending with a key that was NOT uploaded to a keyserver, the message gets never shown in the UI and doesnt seem to get fetched in synching soledad. 

Signature status is still weird, but not part of this issue.

Details:
encrypted not signed = ok (no signature flag)
not encrypted, not signed = ok (no signature flag)
not encrypted, signed = ok (no signature flag, writes signature into body)
encrypted, signed = ok (no signature flag, no signature in body)
encrypted with unknown key and signed = not shown in UI

**Comment by shyba** [comment]
"failure" is now converted by service (mail.py) and understood by web-ui.
I also added a message from this [gist](https://gist.github.com/lqust/a19e5be212c7539da996#file-gistfile1-txt).
The encryption-failure message is too confusing and needs key validation to make sense.
So I changed it for "Message was encrypted but we were not able to decrypt it.".

**Comment by lieblingswelt** [comment]
Encryption flag now works! 
Signature flags are not shown at all or not correctly which is a little confusing, but that is part of Issue #316
