### ISSUE TITLE
Tags are clickable when side bar is collapsed

### ISSUE THREAD

**Issue by dudadornelles** [pixelated-project/pixelated-user-agent#302]
It feels weird, I click on something I don't know what it is and then something happens in the mail list.

![screen shot 2015-02-22 at 4 18 05 am](https://cloud.githubusercontent.com/assets/249770/6317800/998beb00-ba49-11e4-9861-4240f0aa9810.png)

We should either expand the nav if the user clicks somewhere around the tags or not allow it (and allow clicking on "Tags" to expand the nav).

**Comment by tiagoferraz** [comment]
Last week it was the 1st release of the new sidebar by @albogabriel and @apretto , but there is more to come including your suggestion.

**Comment by albogabriel** [comment]
Issue #296 should deal with the tags section on the sidenav; I've explicitly included your comment on making this part not-clickable when the sidenav is collapsed, @dudadornelles - thanks for pointing that out!

I'll close this one as it makes sense to address this issue on #296.
