### ISSUE TITLE
Explain as easily as possible how to get started working with the Pixelated User Agent

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#311]
## Why
In order to have more contributions we need to make it easy for contributors and potential users to set up their user agent instances

## Definition of done
* There is a getting started guide that works for the user agent
* There is a process in place to keep the getting started guide up to date
* Any steps that are deemed 'too hard' right now have stories to automate/simplify them

---

## Notes
From https://github.com/pixelated-project/pixelated-user-agent/issues/283:
When I tried to install locally I had to ask for help to configure the provider credentials and understand how it works and which one is used for development.

Would be great for others newcomers get this step detailed on README.

By the way, when I got help, I was instructed to use try.pixelated-project.org as a provider. Is this the right provider for development?

[ @dudadornelles answered: https://dev.pixelated-project.org/ should be the one used for development. ]

I would include in the Quickstart session some information that tells me where the provider is and how can I sign up for it.

Another option is to put it in the Service session which could be clearer saying the same thing as above.

**Comment by rafaelzlisboa** [comment]
in the pixelated-user-agent there's doc/first-steps.md which seems like a good place to start this from

**Comment by lieblingswelt** [comment]
I needed to run ./go build on the web-ui otherwise this happened:
![screen shot 2015-03-13 at 16 45 46](https://cloud.githubusercontent.com/assets/5365960/6642014/e07f52e2-c9a1-11e4-9e4f-44159711bff9.png)

**Comment by bwgpro** [comment]
@lieblingswelt If you were following the instructions you probably ran the ./go test on the web-ui.
I was suspicious of that and I just checked that when you run the tests it cleans the css and never rebuilds it. I just fixed that, could you please re-test it?
