### ISSUE TITLE
I want to be able to send an encrypted email to a key with utf8 chars.

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-user-agent#322]
Given I have an pgp key and the respective "registered" name consists umlauts (or is UTF8 encoded, respectively) . Example: Föö Bär &lt;foo.bar@somedomain.tld&gt;

When I send an email from a pixelated account to that address,
I want this email to get encrypted

Actually:
I receive a plaintext email

**Comment by fbernitt** [comment]
You can verify that now by:

- Create a new user on staging.pixelated-project.org and log in
- Compose a mail to someone with special chars in their name but don't actually send the mail
- Wait till the colored line under the to email address apears in green

If you need an example email, ping me

**Comment by tiagoferraz** [comment]
I sent email to Tiägo Ferräz <tmartins@thoughtworks.com> from Staging and I received a encrypted email. 
So it is working
