### ISSUE TITLE
Fix Pixelated logo on Staging

### ISSUE THREAD

**Issue by albogabriel** [pixelated-project/pixelated-user-agent#327]
## Why

Currently, staging isn't displaying the entire logo. This is how it is shown locally:

![image](https://cloud.githubusercontent.com/assets/350155/6676744/f5ca1fce-cc08-11e4-9ade-9e21b1f61d41.png)

While on staging, this is what happens:

![image](https://cloud.githubusercontent.com/assets/350155/6676755/08765926-cc09-11e4-8dc1-c45076a310ba.png)

The svg is an actual code (not a referenced file .svg file).

The latest versions on te repo are OK, but for some reason, deploying isn't putting the rest of the code there.

The svg code can be found on https://github.com/pixelated-project/pixelated-user-agent/blob/master/web-ui/app/index.html between lines 24 and 45 the "svg" tag. 

## Definition of Done

It looks on staging as it does on localhost, i.e., the logo also has the "Pixelated" text next to it.

**Comment by re-nobre** [comment]
We need this to be working also on try.pixelated
