### ISSUE TITLE
Instalation of Node in Vagrant boxes should use apt-get

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#328]
## What
Certificate on https://npmjs.org/ expired and ```shell curl -k``` is not recommended. It should use Apt-get to install it 

## I know it is Done when
Install of pixelated does not fail and NPM is installed without exposing the user to threats , i.e not using ```shell curl -k```.

**Comment by varac** [comment]
the last time i checked, i didn't find a debian package that would install on debian stable. 
i might be wrong, if anyone finds a trusted package that we can use i would highly appreciate this.

but https://npmjs.org/ renewed it's certificate so this is not too much of a problem now.
there are packages for next debian stable btw.

**Comment by fbernitt** [comment]
It seems currently there is no alternative to doing the curl install for npm on debian wheezy. See https://github.com/joyent/node/wiki/backports.debian.org

**Comment by varac** [comment]
i suggest that we just close this one, @tiagoferraz or do you want to look for npmjs debs out there ?

**Comment by tiagoferraz** [comment]
@varac sure
