### ISSUE TITLE
Welcome email on first log in

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#334]
## Why
New accounts should have a "welcome" email when they first log in. The inbox looks awfully empty when a user logs in today. A welcome message should be a good opportunity to tell a new user about features and how Pixelated Mail works.

## Definition of done
Given a new account was created
When the user logs in successfully with this account for the first time
Then there's a message with the following content (@albogabriel, please check/refine):

Subject: "Welcome to Pixelated Mail"
Body:
Welcome to Pixelated Mail a modern email with encryption. Pixelated Mail is an open source project that aims to provide secure email on the browser with all the functionality we've come to expect of a modern email client.

**How to use it**
Pixelated Mail should provide functionality that is similar to what you've come to expect of your email software. To the left, you will find a navigation bar that provides access to all your mailboxes and tags. Clicking on them will load the corresponding messages on the middle pane - the mail list. Clicking on a message will load it on this pane, but you know it already!

To compose a message look for the big blue button on the top left. You can add tags to received messages by clicking on the "+" sign under the message subject. You can also find the encryption status of messages just above the sender/recipient information.

**A bit more about Pixelated**
Pixelated is an open source project licensed under AGPL 3.0. It is composed of 3 main parts, the User Agent (what you are using right now), the Dispatcher (what allows you to log in with different accounts to the same instance) and the Platform (which provides the email service you  will use to send and receive messages - the server behind the @ sign on your new mail address). You can learn more by visiting https://pixelated-project.org/.

Enjoy your secure messaging!

**Comment by neissi** [comment]
I did QA using: git@github.com:shyba/pixelated-user-agent.git, I registered a new user(dev.pixelated-project.org) and when I logged at the first time, I received a welcome mail, it's ok, but the status of message was:  Message was readable during transmission. 
Shyba and I agree that is not right status. I think we could discuss more about it tomorrow.

**Comment by neissi** [comment]
This card was blocked until we decide the best way to deal with status of welcome mail.

**Comment by neissi** [comment]
Yesterday after all suggestions in the irc channel, we decided keep the current status of encryption in the message: Message was readable during transmission,  and add some information, brief explanation about message encrypted and authenticity it in the body.

**Comment by GavinSchalliol** [comment]
Should this welcome message be part of the preloaded data we are adding in issues #335-344?
