### ISSUE TITLE
Demo accounts should have preloaded encrypted unread messages

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#335]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 2 encrypted unread messages in the inbox.

## Notes
This story includes putting together the infrastructure to preload data. It would be good if the preload routines are not bound to specific account Ids. Instead it could for example be a script that gets the account credentials and then directly inserts all mails into the sqlite/soledad database. This story is the first in a sequence that all add different types of mails into the account and way the script works should therefore be able to handle more than two mails.

Here is an overview of all data we are eventually planning to preload, with reference to their issue numbers:

Issue | Data Type | Count
----- | --------- | -----
#335 | **Encrypted unread messages** | **2**
#336 | **Encrypted read messages** | **4**
#337 | **Drafts** | **2**
#338 | **Sent messages** | **2**
#339 | **Plain text messages** | **3**
#340 | **Messages with tags** | **7**
 | _Tagged with [tag A] and [tag B]_ | _2_
 | _Tagged with [tag A] only_ | _3_
 | _Tagged with [tag C]_ | _2_
#342 | **Messages in trash** | **3**
#343 | **Forwarded messages** | **2**
#344 | **Replies to messages** | **4**
 | _Replies to the same message_ | _2_
 | _Replies to another message_ | _1_
 | _Reply to a reply_ | _1_

**Comment by tiagoferraz** [comment]
I encountered a few problems.
1. I could not find anywhere how to execute this command and the help messages were not clear. So I had to check the code.  Also, I know I had to execute this command by reading the commit messages here, so some discussion on how this story was implemented are lacking. 
2. I executed the following command passing the Staging fingerprint:
```pixelated-maintenance -lf 1B:4F:20:12:2C:CA:17:33:DD:FB:2E:01:2E:27:C0:CB:35:42:8D:90 -c pixelated.example --debug load-mails file mediumtagged```
It never finished and had some issues. I used a recently created user "seya", I started user agent before running ```load-emails```, so local DB was created. After going through all emails to load it errors out and seems to hang.
```
[04-22 17:08:13] leap-wheezy leap.soledad.client.sync DEBUG    Soledad sync: there are 1794 documents to send.
leap.soledad.client.sync: DEBUG    Soledad sync: there are 1794 documents to send.
[04-22 17:08:13] leap-wheezy leap.soledad.client.sync DEBUG    Soledad source sync info:
  source target gen: 264
  source target trans_id: T-7af7120224df4bb0a7bc3744913adfdc
leap.soledad.client.sync: DEBUG    Soledad source sync info:
  source target gen: 264
  source target trans_id: T-7af7120224df4bb0a7bc3744913adfdc
[04-22 17:08:13] leap-wheezy leap.common.events.client DEBUG    Sending signal to server: event: SOLEDAD_SYNC_SEND_STATUS
content:
leap.common.events.client: DEBUG    Sending signal to server: event: SOLEDAD_SYNC_SEND_STATUS
content:
[04-22 17:08:13] leap-wheezy leap.soledad.client.target DEBUG    Soledad sync send status: 0/1794
leap.soledad.client.target: DEBUG    Soledad sync send status: 0/1794
[04-22 17:08:20] leap-wheezy leap.soledad.client.target WARNING  Soledad sync: error while sending document 1/1794: 
leap.soledad.client.target: WARNING  Soledad sync: error while sending document 1/1794: 
[04-22 17:08:20] leap-wheezy leap.soledad.client.target WARNING  Soledad sync: failing gracefully, will recover on next sync.
leap.soledad.client.target: WARNING  Soledad sync: failing gracefully, will recover on next sync.
[04-22 17:08:20] leap-wheezy leap.soledad.client.target WARNING  Soledad sync: cancelling sync threads...
leap.soledad.client.target: WARNING  Soledad sync: cancelling sync threads...
[04-22 17:08:20] leap-wheezy leap.soledad.client.target WARNING  Soledad sync: cancelled sync threads.
leap.soledad.client.target: WARNING  Soledad sync: cancelled sync threads.```

After waiting a while, a hit ctrl+c and started the user agent, the agent UI never loaded, even after rebuilding the vagrant machine.

**Comment by fbernitt** [comment]
This problem is related to soledad. As soledad currently does not auto-recover there is the sync command. In your case:

```
pixelated-maintenance -lf 1B:4F:20:12:2C:CA:17:33:DD:FB:2E:01:2E:27:C0:CB:35:42:8D:90 -c pixelated.example --debug sync
```
To avoid that problem make sure there is no user agent running while you load the mails.

**Comment by tiagoferraz** [comment]
This is a good a performance test, since the emails just appeared in my inbox. How could I monitor soledad to verify the bottlenecks? What else would be good to monitor?
