### ISSUE TITLE
Demo accounts should have preloaded encrypted read messages

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#336]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 4 encrypted read messages in the inbox.

## Notes
This story depends on https://github.com/pixelated-project/pixelated-user-agent/issues/335

**Comment by lieblingswelt** [comment]
We want to use the state of this to gain more insights into the "name or service not known" error.

**Comment by tiagoferraz** [comment]
I got an error while executing the maintanance command to load emails. 
```shell 
	    result = g.send(result)
	  File "/vagrant/service/pixelated/maintenance.py", line 171, in load_mails
	    add_mail_folder(account, maildir, 'INBOX', deferreds)
	  File "/vagrant/service/pixelated/maintenance.py", line 152, in add_mail_folder
	    for mail in maildir:
	  File "/usr/lib/python2.7/mailbox.py", line 108, in itervalues
	    for key in self.iterkeys():
	  File "/usr/lib/python2.7/mailbox.py", line 362, in iterkeys
	    self._refresh()
	  File "/usr/lib/python2.7/mailbox.py", line 498, in _refresh
	    mtime = os.path.getmtime(self._paths[subdir])
	  File "/home/vagrant/user-agent-venv/lib/python2.7/genericpath.py", line 54, in getmtime
	    return os.stat(filename).st_mtime
	exceptions.OSError: [Errno 2] No such file or directory: '/vagrant/service/mediumtagged/new'
```
Yes, dir '/vagrant/service/mediumtagged/new' does not exist and it was not passed , I see it was changed in commit https://github.com/pixelated-project/pixelated-user-agent/commit/4a0e23cf0b94ce1d9e4d8664532989ddd994dc88. It seems it was not properly tested.
