### ISSUE TITLE
 Demo accounts should have preloaded drafts

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#337]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 2 draft messages.

## Notes
This story depends on https://github.com/pixelated-project/pixelated-user-agent/issues/335

**Comment by neissi** [comment]
I did Qa using a new account and run a pixelated-maintenance, and works well, I saw the preloaded drafts in this account.
