### ISSUE TITLE
Demo accounts should have some preloaded plain text messages

### ISSUE THREAD

**Issue by re-nobre** [pixelated-project/pixelated-user-agent#339]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 3 plain text messages in his or her inbox.

## Notes
This story depends on #335

**Comment by lieblingswelt** [comment]
depends on https://github.com/pixelated-project/pixelated-platform/issues/57

**Comment by jeffhsta** [comment]
I am closing this issue because we already have preloaded plain text mails on CD for TRY environment
