### ISSUE TITLE
Demo accounts should have preloaded tags

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#340]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 3 different tags.
5 messages are tagged with the first tag.
Of those 5, 2 are tagged with the second tag.
2 different messages are tagged with the third tag.

**Comment by bwagnerr** [comment]
We got basic loaded messages on the accounts and this is enough for now, this doesn't make sense for now
