### ISSUE TITLE
Demo accounts should have some encrypted messages

### ISSUE THREAD

**Issue by re-nobre** [pixelated-project/pixelated-user-agent#341]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 2 or more of received messages are encrypted.

## Notes
This story depends on #335

**Comment by lqust** [comment]
Feature will be implemented as part of #335
