### ISSUE TITLE
 Demo accounts should have preloaded messages in trash

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#342]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 3 messages in trash.

## Notes
This story depends on https://github.com/pixelated-project/pixelated-user-agent/issues/335

**Comment by bwagnerr** [comment]
We got basic loaded messages on the accounts and this is enough for now, this doesn't make sense for now
