### ISSUE TITLE
Demo accounts should have preloaded some forwarded messages from received messages

### ISSUE THREAD

**Issue by re-nobre** [pixelated-project/pixelated-user-agent#343]
## Why
Currently, when one log in with alice, eve or bob on try.pixelated-project.org, he or she will see a very empty inbox. We believe that by putting a good variety of realistic messages there, the users will be more inclined to explore.

## Definition of Done
Upon logging in with one of the test accounts, a user will see 2 or more forwarded messages from received messages.

## Notes
This story depends on #335

**Comment by bwagnerr** [comment]
We got basic loaded messages on the accounts and this is enough for now, this doesn't make sense for now
