### ISSUE TITLE
Automatically reset data in demo accounts after a day

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#346]
## Why
Someone can use the demo to send a "Pixelated Sucks" message. That would be bad publicity for us :o). We want to make sure that the demo environment represents a fairly reasonable use of Pixelated Mail.

## Definition of Done
Given I have sent lots of gibberish on a demo account on try.pixelated-project.org
When 24 hours pass
Then that gibberish is not there anymore
And the preloaded data set was loaded

**Comment by cz8s** [comment]
I think it would be better to keep mails longer. We run into lot of problems with old and stale mails at the moment and this is the best way to see these bugs in the wild.

**Comment by bwgpro** [comment]
@cz8s I don't agree, I think we should keep mails for a short time because we suffer heavily from client degradation today, the client basically explodes at old or stale mails, if we keep that fresh, one less problem for now until we sort the client issues.

**Comment by shyba** [comment]
I agree with everyone:
"Try" should not keep mails longer because of gibberish and stability, but
we need to let staging or just one separated account in try with a heavy
inbox to find those bugs.
Sounds reasonable?
It could also be in staging or some other env prepared to be braking more
often.

2015-06-19 21:53 GMT+02:00 Bruno Wagner Gonçalves <notifications@github.com>
:

> @cz8s <https://github.com/cz8s> I don't agree, I think we should keep
> mails for a short time because we suffer heavily from client degradation
> today, the client basically explodes at old or stale mails, if we keep that
> fresh, one less problem for now until we sort the client issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pixelated-project/pixelated-user-agent/issues/346#issuecomment-113624375>
> .
>



-- 
Victor Shyba

**Comment by cz8s** [comment]
How about the other way around? try should be 'live' with lots of emails and then we have staging which gets deleted regularly?

**Comment by cz8s** [comment]
@jeffhsta: we are preserving the data after a new deploy. We have a extra partition with all the data
on it. If we move the data from that partition back to where it usually is, it will be empty after each deploy. That would solve this ticket very easily. Then we only need to create the accounts again.
Which should be just one curl command.
On the other hand, the users would get a new gpg key after every deploy. But that shouldn't be a problem.
