### ISSUE TITLE
Mail client should not be so strict with wrongly encoded header fields

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-user-agent#347]
Why

When a mail with not correctly set header fields, for example for To or Subject, arrives, it currently fails to parse it.

A mail could be produced like this:
```
swaks --from fbernitt@thoughtworks.com --h-From: '"Fölker Börnitt" <folker@staging.pixelated-project.org>' --to folker@staging.pixelated-project.org
```

Requirements:
When a mail with wrongly encoded header fields arrives, the parsing should run a best effort approach and just replace invalid characters with underscores, but aside from that not affect the parsing.

The parsed mail should be visible in the mail list and there shouldn't be an exception about parse problems in the logs

**Comment by fbernitt** [comment]
This is also true for all other header fields,

**Comment by tiagoferraz** [comment]
besides model.py and fields.py, where can I find other headers Pixelated use?

**Comment by tiagoferraz** [comment]
I blocked the story while the defects are fixed.

**Comment by fbernitt** [comment]
This should be a list of headers we seem to process:

From
To
Cc
Bcc
Subject
Date
Received
Content-Type
Content-Description
Content-Transfer-Encoding
Final-Recipient
X-Pixelated-encryption-status
X-Pixelated-encryption-status
X-Leap-Signature

I 'grep'ed them from the sources.

**Comment by tiagoferraz** [comment]
Thanks, I will test it extensively.
