### ISSUE TITLE
Send button stuck on "Sending" when "problems to talk to server" occurs

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#349]
## What
The Send button on get stucked in "Sending" when User Agent cannot talk to server and there is no workaround the defect.

## How
One way to reproduce it is to cause a problem of the user agent to talk to server:
1. Start user agent 
2. Compose a new email 
3. Stop user agent
4. Click on Send

## Expected
After a error occurs during Send, the button should be in "Send" status.

**Comment by neissi** [comment]
I did  following Tiago's steps and works properly.
