### ISSUE TITLE
Email is sent but user is informed otherwise

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#350]
## What
Many of us experienced during testing in Try and Staging that the email is actual sent but got informed of problems during sending occurred. 

## Why
Why it occurs or how to reproduce is not clear. It happens often but what is causing it is not clear. 

## Expected
The feedback to user should be always true and the clear as possible. If a problem did not occurred, then the user should see "email sent"

**Comment by jeffersonhsta** [comment]
I tried reproduce this bug on my box and on TRY environment, but on both this bug didn't happen.
Probably this bug was fixed without following this issue.
