### ISSUE TITLE
Send button is enabled with any text on recepient 

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#351]
## What
Send button is enabled with any informed string on To, Cc or Bcc, including invaliding ones

## Why
User is informed of invalid emails  on recipients after it pressed Send

## Expected
User should be informed of invalid emails before send it

**Comment by shyba** [comment]
This is [very polemic.](http://stackoverflow.com/a/815232)

I think we need just a very basic one without false negatives. Just to catch big mistakes.
Like this one: /\S+@\S+\.\S+/

Will use this one, unless someone is against it.

**Comment by jeffersonhsta** [comment]
This Issue is basically done.
The send button is enabled even when an invalid email address is wrote, but when this button is clicked, the user receive a message "One or more of the recipients are not valid emails"

Another issue will be open to solve UX proposes
