### ISSUE TITLE
Emails sent to myself form myself takes to long to appear on inbox

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#352]
## What
This is a performance issue, the cause should be investigated and explained to the team before fixing it. 
When sending email from myself to myself, it takes a good while to appear on inbox when it is expected to be very fast. This leaves the user in a void and causes some confusion , like when Pixelated informs that a error occurred during sending but it actually was sent. 

## Expected
User expected to the emails appears quick in inbox.

**Comment by dudadornelles** [comment]
I believe what happens is the following:
- Mail gets sent to the LEAP provider. 
- Mail is received by the LEAP provider and stored as raw in a folder. 
- leap_mx sees that there is an email in that folder, finds out which to who it should deliver the mail, encrypts the mail with that user public key and stores it in the user "table" on CouchDB. 
- LeapMail (on the user agent) pools soledad for new documents every 15 secs if I'm not mistaken. Once it finds out that there is a new mail, it will sync it as 'raw' to the db.
- Another process in LeapMail will decrypt the 'raw' mail and create proper soledad documents that represent that mail. When this happens we also index that mail on the search index.
- The UI eventually will refresh itself (every 10 secs) and you will finally see your own mail.

One solution would be to not even send that mail to LEAP provider and just add it on your Inbox (the same way we do for when we have errors on sending mails where we add error messages to the user inbox).

**Comment by bwagnerr** [comment]
Closing this for now, we'll revisit performance issues once we get things working with the latest LEAP libraries head
