### ISSUE TITLE
Button Send is enabled when there are no recipients

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#353]
## What
Button Send is enabled when there are no recipients when replying to a email

## How
1. Choose to reply an email
2. Delete recipients 
3. Send is enabled

## Expected
Button should be disabled

**Comment by albogabriel** [comment]
Problem still occurs, but only when replying - when composing a new email, clearing the "to" input works. When replying, the send button is still enabled.

Would you have an idea why, @lieblingswelt ?

**Comment by lieblingswelt** [comment]
It is working on staging and it should have for the past 23hrs. Maybe we should take a look together later today?

**Comment by albogabriel** [comment]
I was able to verify that it is working properly on staging now. Thanks, @lieblingswelt!
