### ISSUE TITLE
Bcc email is shown on header

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#354]
## What
Emails in Bcc are shown in header

## Expected
They should not be shown

![screen shot 2015-03-25 at 6 56 39 pm](https://cloud.githubusercontent.com/assets/2946807/6836416/85bb5fd0-d320-11e4-9909-80945c35c3da.png)

**Comment by dudadornelles** [comment]
Is this on the "sent" mailbox? If yes then it should be fine that who sent
the bcc knows the addresses.

**Comment by tiagoferraz** [comment]
No. It appears on the Inbox.
![screen shot 2015-03-26 at 11 38 49 am](https://cloud.githubusercontent.com/assets/2946807/6848508/615afaa6-d3ac-11e4-81bf-e4a5114b86aa.png)

**Comment by tiagoferraz** [comment]
Putting it here from RFC 2822 for easy of consultation
 The "Bcc:" field (where the "Bcc" means "Blind Carbon Copy") contains
   addresses of recipients of the message whose addresses are not to be
   revealed to other recipients of the message.  There are three ways in
   which the "Bcc:" field is used.  In the first case, when a message
   containing a "Bcc:" field is prepared to be sent, the "Bcc:" line is
   removed even though all of the recipients (including those specified
   in the "Bcc:" field) are sent a copy of the message.  In the second
   case, recipients specified in the "To:" and "Cc:" lines each are sent
   a copy of the message with the "Bcc:" line removed as above, but the
   recipients on the "Bcc:" line get a separate copy of the message
   containing a "Bcc:" line.  (When there are multiple recipient
   addresses in the "Bcc:" field, some implementations actually send a
   separate copy of the message to each recipient with a "Bcc:"
   containing only the address of that particular recipient.) Finally,
   since a "Bcc:" field may contain no addresses, a "Bcc:" field can be
   sent without any addresses indicating to the recipients that blind
   copies were sent to someone.  Which method to use with "Bcc:" fields
   is implementation dependent, but refer to the "Security
   Considerations" section of this document for a discussion of each.

**Comment by tiagoferraz** [comment]
2 Updates: I did 2 more test cases:
1. I sent an email from: tiago.ferraz@gmail.com to: tony@dev.pixelated-project.org bcc: tmartins@thoughtworks.com.
Result: * The email in bcc is not shown * 
2. I sent an email from: tiago.ferraz@gmail.com bcc: tony@dev.pixelated-project.org; tmartins@thoughtworks.com.
Result: * None email is shown in header, instead user reads "Undisclosed Recipients".

Therefore, I am closing this since it is not a defect.
