### ISSUE TITLE
UI breaks when bower is updated

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#356]
## What 
Started investigating why pipeline user-agent-dependencies-upgrade-tests breaks at functional tests. I did the following:
1. I upgrade npm using npm-check-updates -u
2. Executed the tests, all functional tests passed.

3. I upgrade the bower packages using bower-update
4. Executed the tests, all tests failed.

## Why 
Started pixelated user agent, and the UI does not complete to load. This error can be found
```javascript 
ReferenceError: _ is not defined
````

## Expected
UI should load without errors.

**Comment by bwagnerr** [comment]
The pipeline doesn't exist anymore, so I'm closing this issue
