### ISSUE TITLE
Not all HTML email is rendered

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#357]
## What
I sent an email from gmail account with HTML elements and observed the following errors:
1. italic & bold and crazy colors words are not displayed and do not show on source.
2. The "Thoughtworks" on my signature is an anchor with an image to Thoughtworks site. The image is not displayed , but the anchor is loaded and clickable (security breach?!)

![screen shot 2015-03-31 at 11 17 47 am](https://cloud.githubusercontent.com/assets/2946807/6921188/94b8b988-d799-11e4-975b-a65dcc234f14.png)
![screen shot 2015-03-31 at 11 18 08 am](https://cloud.githubusercontent.com/assets/2946807/6921191/9631ac3e-d799-11e4-8e92-8648b7bf114d.png)

## Expected
All formated text should be rendered correctly or at least strapped of format. 
Anchors should not be sanitized

**Comment by bwgpro** [comment]
Italic was not on the whitelist so I added it.
The image tag is stripped, but the links shouldn't be, considering that link has nothing more, I think the result is correct
