### ISSUE TITLE
SSL errors should be treated and a help message should be presented.

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#375]
## what 
When the user starts the user agent to a provider with not a official certificate without the correct parameters, it prints a stack trace because the certificate could not be verified.

## Expected
This exception should be treated and the user should be presented with a help error message and/or the help message showing the parameters

**Comment by shyba** [comment]
Proposed error message:
SSL Error: Please check your certificates or read our wiki for further info: [[SSL page on wiki]]

This way we can reuse the wiki page for SSL errors by dispatcher as well.

**Comment by cz8s** [comment]
We different problems with SSL. Would it be possible to tell the user to which host the user-agent tried to connect, which ssl cert it got (subject and fingerprint) and what the user-agent was expecting?

**Comment by bwgpro** [comment]
We changed the message on friday to include the original error. We could see (fingerprint mistmatch - expecting <this>, got <that>). Would that be enough? Any newer PixUA image should have that

**Comment by shyba** [comment]
[Habemus help!](https://github.com/pixelated-project/pixelated-user-agent/wiki/Configuring-and-using-SSL-Certificates-for-LEAP-provider)
Feel invited to review.

**Comment by tiagoferraz** [comment]
Final result
![screen shot 2015-04-20 at 4 20 49 pm](https://cloud.githubusercontent.com/assets/2946807/7238472/181ae5a0-e779-11e4-8255-ffb18293cad0.png)
