### ISSUE TITLE
Improve User Agent Readme

### ISSUE THREAD

**Issue by lieblingswelt** [pixelated-project/pixelated-user-agent#378]
**AS** a new user who wants to try the Pixelated user agent
**I WANT** the readme to be clear and easy to follow
**SO THAT** I can get started quickly with trying Pixelated

# Background
We gathered some feedback from an external developer, who tried to start using the user agent using the readme as a starting point. This card will involve a package of changes to the readme in order to make it more user-friendly.

# Suggested changes
* **Provider:** remove alternative options for leap providers, since they are not usable in this context (mostly not offering email at the moment).
* **Requirements:** 
    * Include a note explaining what role virtualbox and vagrant play in the setup process
    * Make it clear that the installation process holds virtualbox images and writes them to the virtualbox automatically
    * "virtualbox" and "vagrant" should link to their official pages
* Make it clear what component of Pixelated is required for doing what -- for example, the platform is not needed for testing only the user agent. An architecture overview (as found on the platform page) would be helpful.

**Comment by GavinSchalliol** [comment]
**Removed the following line:**
- use official cert on dev.pixelated-project.org, so the user is not confronted with the insecure connection warning.
**Reason:**
Split off as #379

**Comment by GavinSchalliol** [comment]
I consulted with the dev who gave us feedback and edited the post to organize/elaborate on some of these points. Send me a message if you have any questions!

**Comment by rafaelzlisboa** [comment]
i don't know who gave the feedback but i'd like to assign this person to QA this :ship:

**Comment by tiagoferraz** [comment]
I read the document and it is a very detailed explanation on how to get started. Maybe we should also add an explanation about the environments since we just say to connect to dev.
