### ISSUE TITLE
Update user-agent to work with leap 0.7

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-user-agent#382]
Why
===

LEAP 0.7 has many changes and we should update our application to make sure we're testing against the latest stage. Soledad has been facing problems on try and it might be fixed in case we use a newer LEAP version.

Definition of done
===============

The Pixelated user-agent should work with LEAP 0.7.

Notes
=====

- need to discuss our strategy for 0.6 support

**Comment by varac** [comment]
@rafaelzlisboa  unstable.pixelated-project.org ist running platform 0.7, see https://github.com/pixelated-project/project-issues/wiki/platform-enviroments#unstablepixelated-projectorg

**Comment by rafaelzlisboa** [comment]
@varac :+1: 

I'll try to keep a task list of what we identified so far (these will become separate issues if they're more complicated):

[ ] changes in SRP
[ ] soledad fails on startup with `nodename nor servname provided, or not known`

**Comment by rafaelzlisboa** [comment]
changes in SRP:

we have created leap.auth (https://pypi.python.org/pypi/leap.auth). the code lives in our handle in github (pixelated-project/leap_auth), but can be moved to leap's as soon as they want.

now we need to create a debian package and then update our code to use it.


soledad failures:
@varac fixed it :dancer:

**Comment by rafaelzlisboa** [comment]
debian package is created and available in our snapshot repos

**Comment by rafaelzlisboa** [comment]
installed pixelated-dispatcher on unstable.pixelated-project.org (LEAP 0.7).
the newer user-agent version is also on try/staging (LEAP 0.6)
