### ISSUE TITLE
soledad client sync is slow

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-user-agent#393]
Why
===

@fbernitt wrote a soledad client and turns out it's much faster than the user-agent. we should identify ways of making our sync faster.

Definition of done
==============

Have a clear view of what's causing it and issues to fix it if applicable.

**Comment by GavinSchalliol** [comment]
(Timeboxed until Thursday 21 May, as per discussion at standup today)

**Comment by GavinSchalliol** [comment]
@rafaelzlisboa @bwgpro Does this still need to be a ticket?

**Comment by bwgpro** [comment]
@shyba is probably in a better position to answer this.

Shyba, do we have any fixes we can do to make this better in the short term, is it worth the effort?

**Comment by shyba** [comment]
It is becoming faster, the worst part was the old sync target which now uses async http from Twisted. Other parts are also being migrated/optimized. This issues makes no sense by now, as there is no simple way speed it up.
Performance issues are being addressed on 0.7 and 0.8 releases. This card was useful for better understanding Soledad internals, but it is too broad on description.
We can propose more specific changes to speed up after full migration to 0.7, but it's not worth for 0.6
Closing card, as explained.
If anyone has ideas on how to improve it, make a PR there or open a more specific card here.
