### ISSUE TITLE
Querying local documents is slow

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-user-agent#394]
Why
===

During our profiling tests, we have identified many calls to sqlcipher.

We need to assess how slow those operations actually are and if it's worth changing something to make it faster.

Definition of done
==============

Have a clear view of what's causing it and a strategy/issues to fix it if applicable.

Notes
=====

- SQLCipher is not slow - the problem is the amount of calls we have and maybe there is a way to decrease it.
- The Index is updated every time a document is inserted. Is this ideal?
- Verify the operations we do in SQLCipher

**Comment by GavinSchalliol** [comment]
(Timeboxed until Thursday 21 May, as per discussion at standup today)

**Comment by GavinSchalliol** [comment]
@rafaelzlisboa @bwgpro @jeffhsta Does this still need to be a ticket?

**Comment by bwgpro** [comment]
This is still an issue, but considering it makes no sense for us to pin this down on bitmask 0.6, and we halted the 0.7 change by now, I see no clear path to do this or create actionable stories based on this.
