### ISSUE TITLE
User-agent doesn't recover after LEAP provider error

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-user-agent#395]
Why
===

When there is a problem with the LEAP provider or in the connection between the user-agent and the provider, the application doesn't react well.

Definition of done
=============

We have a clearer definition of what's not going well, a list of cases in which this occurs, and issues to fix them are created.

Notes
=====

- Try out the newer version of the LEAP libraries

**Comment by bwagnerr** [comment]
This doesn't make sense anymore, we will be working with LEAP head and have other issues to deal with that
