### ISSUE TITLE
Handle missing user databases on LEAP provider

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-user-agent#396]
Why
===

Given the asynchronous nature of user creation in LEAP, it might be possible that when a user creates an account at the LEAP provider, its database does not exist yet.

If the user tries to login to Pixelated right after creating her account, there is a slight chance that her database is not ready, and the initial setup will obscurely fail (i.e. no feedback to the user will be given). 

Definition of done
==============

We have found/discussed a way to detect when the user database is not yet created and issues to fix it, if applicable.

**Comment by bwagnerr** [comment]
This is a tapicero issue and not really related to the pixelated user agent. There's no way to detect if a user database exists on the server because it won't give us info on that. Closing this and using the latest libraries we run into this issue again we can review this
