### ISSUE TITLE
SRP token expiry handling

### ISSUE THREAD

**Issue by rafaelzlisboa** [pixelated-project/pixelated-user-agent#397]
Why
===

After running for some time (something around 1 or 2 days), a user agent will start raising errors related to expired SRP token, using lots of CPU and increasing memory usage. We believe this is caused by the fact we don't handle token expiration properly.

Definition of done
=============

Expired token doesn't cause this problem anymore

**Comment by bwagnerr** [comment]
We are unclear if this will be an issue using the latest bitmask libraries, I'll close this for now and we can revisit it if this problem come up again
