### ISSUE TITLE
Remove local SMTP

### ISSUE THREAD

**Issue by jeffhsta** [pixelated-project/pixelated-user-agent#398]
Why
===

We don't have information on encryption and signature because that happens in another thread, outside of the scope of pixelated and that doesn't give feedback currently
Running a SMTP locally means we run a SMTP locally, another moving part running and using memory

Definition of done
=============

I can send signed and encrypted email without using a local SMTP.
I have feedback about an email signature and encryption process

**Comment by bwagnerr** [comment]
We are unclear if this will be an issue using the latest bitmask libraries, I'll close this for now and we can revisit it if this problem come up again
