### ISSUE TITLE
Research solutions to high memory footprint for docker instances in dispatcher

### ISSUE THREAD

**Issue by fbernitt** [pixelated-project/pixelated-user-agent#400]
The current idea is to spawn a new user agent for each user in the dispatcher setup. It seems the memory consumption is way to high.

This ticket is about researching whether the required amount of memory can be reduced or what alternatives there are.

Requirements:
- Its documented in this ticket how the memory is used
- Possible alternatives have been discussed with the team

**Comment by GavinSchalliol** [comment]
Here is a Google Doc with some research from @shyba: https://docs.google.com/a/thoughtworks.com/document/d/1EjubGh0fqAR5Vz5aEXl4Icz5eJw6DUuEH14Dw08CUM0/edit?usp=sharing

From Shyba's email:
> So far, this huge base memory is marked as 'leaked' on objgraph and as 'dirty' by linux. 

> I also came today with other ideas to force KSM (Kernel Same-page Merge) on Docker/LXC host as described in this docker issue. This should "deduplicate" this huge base memory. There is even a UKSM Project.
> Fortunately, before trying that out a guy on #docker channel pointed me out not one, but two security issues with this crazy approach and told me about virtual bitcoins being hacked. So, dead end here until a KSM expert says otherwise.

**Comment by GavinSchalliol** [comment]
> * Its documented in this ticket how the memory is used

Do we think this part of the ticket has been satisfied? Should we start putting forward solutions, or is more research required?

**Comment by bwgpro** [comment]
I would say the first requirement is done, the second one, discuss with the team and decide on a course of action is still pending

**Comment by bwgpro** [comment]
There is no clear or easy solution right now as far as I see, that is why we can't create well defined solutions before having a conversation.
