### ISSUE TITLE
Pixelated user agent should use the latest bitmask libraries versions

### ISSUE THREAD

**Issue by bwagnerr** [pixelated-project/pixelated-user-agent#401]
In order to assess the problems pointed on issues #393 and #394 we need the user agent to work with the latest bitmask libraries, so we can check for improvements and investigate the other issues as we need

**Comment by re-nobre** [comment]
We had a lot of challenges and halted development on this.
We have to discuss more before continuing.

**Comment by bwagnerr** [comment]
This doesn't make sense anymore, we will be working with LEAP head and have other issues to deal with that
