### ISSUE TITLE
Migrate user agent functional tests to platform repo

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#402]
## Why
The functional tests on User Agent are not using the real dispatcher, with many parts from the LEAP being mocked. In addition, moving the tests to the platform repo where there are other functional tests, would increase maintainability and coverage of the functionalities.

**Comment by tiagoferraz** [comment]
blocked by staging problems.

**Comment by tiagoferraz** [comment]
Unblocked now on staging. I am with one error from staging tests, where the emails is clicked on, but it is not opened on the right pane, the mail on mail list is even marked as read. 
After it, still have to test the user agent tests.

**Comment by cz8s** [comment]
test is green on staging! yay.
