### ISSUE TITLE
user-agent does not know option '--home'

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#405]
docker uses the option '--home' to tell the user-agent where to look for config and database. But when the dispatcher starts docker, I see this error:
```
pixelated-user-agent: error: unrecognized arguments: --home /mnt/user
```

**Comment by cz8s** [comment]
is this related to https://github.com/pixelated-project/pixelated-dispatcher/issues/102 ?

**Comment by rafaelzlisboa** [comment]
seems related to f4f2f0ff3e808bc2c85b914aa750ad68770ed334

**Comment by rafaelzlisboa** [comment]
pushed a fix to dispatcher https://github.com/pixelated-project/pixelated-dispatcher/commit/e143d796351c5580f83c44927af10f629f5b5a32

**Comment by cz8s** [comment]
I now get the next error:
```
pixelated-user-agent: error: unrecognized arguments: --dispatcher-stdin
```
