### ISSUE TITLE
Refactor the user-agent start up

### ISSUE THREAD

**Issue by jeffhsta** [pixelated-project/pixelated-user-agent#406]
Why
===

We have a lot of code that integrate with LEAP on start up of pixelated-user-agent.
Would be better haev a separated code that starts pixelated-user-agent and the code that integrate with LEAP

Definition of done
=============

Can start the pixelated-user-agent even the LEAP session is not already created or the first soledad sync is not done yet.

**Comment by cz8s** [comment]
user-agent starts without problems. Even in docker. 
Everything looks good.
