### ISSUE TITLE
user-agent does not understand config provided by dispatcher

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#409]
when the user-agent gets started in dispatcher, it receives the config on stdin. But the format seems to have changed either in dispatcher or user-agent. I get this error from the user-agent:
```
[twisted] ERROR pixelated.bitmask_libraries.soledad.SoledadDiscoverException: cafile must be None or a byte string
```
But if I start the user-agent by hand inside docker and provide the credentials manually, everything works

**Comment by bwgpro** [comment]
That's sad, it should support unicode strings, I'll fix this on the user agent to always coerce it to a bytestring so this will not be an issue anymore

**Comment by bwgpro** [comment]
Just did it, could you try again after the user agent finished building?

**Comment by cz8s** [comment]
waiting for the build and will give it a try. thanks for the fast fix

**Comment by cz8s** [comment]
works!
