### ISSUE TITLE
Load mails inside test accounts

### ISSUE THREAD

**Issue by neissi** [pixelated-project/pixelated-user-agent#412]
##  **Why**

Currently we don't have a real experience using the test accounts, because the mail list is empty.
To be more realistic, should be fine load some set of mails inside these accounts.

##  **Definition of Done**
I can access the test account and see a variety of mails listed on.

**Comment by jeffhsta** [comment]
The shell script for automate the load mails on CD is done, but we got a problem on sync those emails loaded by maintenace script.

This issue is blocked because we must solve that problem before continue working on this one.

**Comment by cz8s** [comment]
the user-agent docker image was not built since June 19. Thats why the user-agent on try didn't know your new maintenance commands yet. I triggered a build manually. Lets see

**Comment by cz8s** [comment]
the stage in go had a space in front of the script. So it said
```
" ./thoughtworks-ci-config/foo"
```
and not
```
"./thoughtworks-ci-config/foo"
```

Thats why the go-agent then couldn't find the script.... Stupid go.

**Comment by cz8s** [comment]
pipeline is green! yay. But I don't see any new mail in the accounts?

**Comment by neissi** [comment]
I did the steps bellow:

- First of all, I ran the script to clean the test accounts (cleanup-demo-accounts)
- After that I created again Alice, Bob and eve accounts
-  And ran "load mails" 
-  I log in these accounts in try.pixelated and the set of mails are there.

**Comment by bwgpro** [comment]
We should have the clean-up running on the pipeline for now I think, especially because the load mails already is, that would make we have a fresh account state after every deploy. Even though we might like to keep mails for longer, for now I think this is the best solution for having try in a good state
