### ISSUE TITLE
user-agent can't send emails

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#415]
When trying to send an email with the user-agent, 
the ui says 'Couldn't send mail now, try again later.' and I get this error in the console:
```
2015-06-18 07:29:02 [pixelated.bitmask_libraries.smtp] WARNING Couldn't start the SMTP server now, will try again when the user tries to use it
```

**Comment by bwgpro** [comment]
After the latest provider version, the download of the SMTP client certificate depended on the authorization token (in addition to the session_id from before).

I changed the user agent to do this and now the SMTP works correctly

**Comment by cz8s** [comment]
checked with local user-agent againt try.pixelated. And it works. Story can be launched
