### ISSUE TITLE
Question: Is there an easy way to play with the user-agent UI without having to connect to the dev.pixelated service?

### ISSUE THREAD

**Issue by SamuelToh** [pixelated-project/pixelated-user-agent#417]
Hi all,

I was just trying to run the user-agent application using the, once worked, instructions below yesterday evening, But I'm getting some timed-out error message, so I thought the dev.pixelated-project.org could be down.

I have verified this by trying to access the "dev.pixelated-project.org" service through my browser which returned me error "This web page is not available" on Chrome.

I'm just wondering whether Is there an alternate way to bring up the application without having to connect to the dev.pixlated-project.org? This is so that I can still play with the flightJS components  in the pixelated-user-agent? Thanks for the help!

----------- Instructions that i'm using.----------------
To run the user agent:

$ pixelated-user-agent --host 0.0.0.0 -lc /vagrant/service/pixelated/certificates/dev.pixelated-project.org.ca.crt
> 2015-01-23 11:18:07+0100 [-] Log opened.
> 2015-01-23 11:18:07+0100 [-] Which provider do you want to connect to:
dev.pixelated-project.org
> 2015-01-23 11:18:52+0100 [-] What's your username registered on the provider:
username
> Type your password:
*******************

Regards,
Sam

**Comment by bwagnerr** [comment]
Hey Sam,

Sorry for the delay, we got dev.pixelated-project.org up again and we'll keep an eye to keep it running smoothly.

Dev should be working now and that is still the best way to play with the UI currently. If you ever have problems with dev again, you can use the try.pixelated-project.org with any of the Demo users we have there.

Any suggestions on how to make the process smoother or questions please feel free to ask here or on the IRC

Kind regards,
Bruno Wagner

**Comment by SamuelToh** [comment]
Hi bwagnerr,

thanks for looking into the issue. everything looks normal again! 

Yep will head to the IRC chat if I have questions. Thanks again.

Regards,
Sam
