### ISSUE TITLE
Indicate if a recently deployed User Agent package has a critical issue

### ISSUE THREAD

**Issue by lqust** [pixelated-project/pixelated-user-agent#70]
Was: Smoke test minimum functionality for user agent
Created from: https://github.com/pixelated-project/pixelated-dispatcher/issues/16

* Test if the packages are installable and conform to debian policies
* Test if we can connect
* Identify additional test opportunities and add here accordingly
* Maybe run after a staging deploy
* Maybe use piuparts and lintian

**Comment by cz8s** [comment]
this should be almost done. I added tests for the dispatcher and used the same tests for user-agent.
The package gets installed and then pixelated-user-agent is run once. 
Is that enough?

**Comment by neissi** [comment]
After downgrade python packages it looks enough.
